extensions_to_types = {
    "html": "text/html",
    "css": "text/css",
    "js": "application/javascript",
    "json": "application/json",
    "xml": "application/xml",
    "png": "image/png",
    "jpg": "image/jpeg",
    "jpeg": "image/jpeg",
    "svg": "image/svg+xml",
    "gif": "image/gif",
    "ico": "image/x-icon",
    "pdf": "application/pdf",
    "zip": "application/zip",
    "gz": "application/gzip",
}
