# This file is generated by the gen_tf.py script.
# Do not edit this file directly.

module "favicon" {
  source = "./zone_deployment"

  content_type   = "image/x-icon"
  domain_aliases = []
  file           = "favicon.ico"
  file_directory = "../public/"
  fqdn           = "favicon.${var.domainName}"
  source_hash    = filemd5("../public/favicon.ico")
  zone_id        = aws_route53_zone.main.zone_id
}

module "index" {
  source = "./zone_deployment"

  content_type   = "text/html"
  domain_aliases = ["www.${var.domainName}"]
  file           = "index.html"
  file_directory = "../public/"
  fqdn           = "${var.domainName}"
  source_hash    = filemd5("../public/index.html")
  zone_id        = aws_route53_zone.main.zone_id
}

module "sitemap" {
  source = "./zone_deployment"

  content_type   = "application/xml"
  domain_aliases = []
  file           = "sitemap.xml"
  file_directory = "../public/"
  fqdn           = "sitemap.${var.domainName}"
  source_hash    = filemd5("../public/sitemap.xml")
  zone_id        = aws_route53_zone.main.zone_id
}

module "non_breaking_spaces_technical_bites" {
  source = "./zone_deployment"

  content_type   = "text/html"
  domain_aliases = []
  file           = "non-breaking-spaces.html"
  file_directory = "../public/technical-bites/"
  fqdn           = "non-breaking-spaces.technical-bites.${var.domainName}"
  source_hash    = filemd5("../public/technical-bites/non-breaking-spaces.html")
  zone_id        = aws_route53_zone.main.zone_id
}
