# This file is generated by the gen_tf.py script.
# Do not edit this file directly.

output "favicon_cloudfront_distribution_id" {
  value = module.favicon.cloudfront_distribution_id
}

output "favicon_hosted_zone_id" {
  value = module.favicon.hosted_zone_id
}

output "favicon_bucket_id" {
  value = module.favicon.bucket_id
}

output "favicon_bucket_regional_domain_name" {
  value = module.favicon.bucket_regional_domain_name
}

output "favicon_cert_arn" {
  value = module.favicon.cert_arn
}

output "favicon_cert_validation_record" {
  value = module.favicon.cert_validation_record
}


output "index_cloudfront_distribution_id" {
  value = module.index.cloudfront_distribution_id
}

output "index_hosted_zone_id" {
  value = module.index.hosted_zone_id
}

output "index_bucket_id" {
  value = module.index.bucket_id
}

output "index_bucket_regional_domain_name" {
  value = module.index.bucket_regional_domain_name
}

output "index_cert_arn" {
  value = module.index.cert_arn
}

output "index_cert_validation_record" {
  value = module.index.cert_validation_record
}


output "sitemap_cloudfront_distribution_id" {
  value = module.sitemap.cloudfront_distribution_id
}

output "sitemap_hosted_zone_id" {
  value = module.sitemap.hosted_zone_id
}

output "sitemap_bucket_id" {
  value = module.sitemap.bucket_id
}

output "sitemap_bucket_regional_domain_name" {
  value = module.sitemap.bucket_regional_domain_name
}

output "sitemap_cert_arn" {
  value = module.sitemap.cert_arn
}

output "sitemap_cert_validation_record" {
  value = module.sitemap.cert_validation_record
}


output "non_breaking_spaces_technical_bites_cloudfront_distribution_id" {
  value = module.non_breaking_spaces_technical_bites.cloudfront_distribution_id
}

output "non_breaking_spaces_technical_bites_hosted_zone_id" {
  value = module.non_breaking_spaces_technical_bites.hosted_zone_id
}

output "non_breaking_spaces_technical_bites_bucket_id" {
  value = module.non_breaking_spaces_technical_bites.bucket_id
}

output "non_breaking_spaces_technical_bites_bucket_regional_domain_name" {
  value = module.non_breaking_spaces_technical_bites.bucket_regional_domain_name
}

output "non_breaking_spaces_technical_bites_cert_arn" {
  value = module.non_breaking_spaces_technical_bites.cert_arn
}

output "non_breaking_spaces_technical_bites_cert_validation_record" {
  value = module.non_breaking_spaces_technical_bites.cert_validation_record
}

